### ISSUE TITLE
【两个问题】缺少@ant-design/pro-utils依赖，缺少个文件cropper.css

### ISSUE THREAD

**Issue by daoxiaonoodles** [ballcat-projects/ballcat-ui-react#10]
1.依赖可以通过，pnpm install @ant-design/pro-utils --save安装

2.缺少个文件
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                14:40:55
This dependency was not found:
* cropperjs/dist/cropper.css in ./src/components/Cropper/Cropper.tsx

**Comment by lingting** [comment]
你是通过什么安装的依赖? yarn 还是 npm ?

**Comment by lingting** [comment]
yarn 的话, 预览环境就是yarn 构建的, 没有问题
npm 的话, 我刚刚尝试了打包和构建. 也是没有问题的. 我一会把 lock文件传上来. 你更新代码试试
如果是其他的工具的, 欢迎 pr 适配
![image](https://user-images.githubusercontent.com/59352063/183836482-a5fefd3b-ee59-4401-89ac-b069c7e3dfd9.png)

**Comment by daoxiaonoodles** [comment]
> yarn 的话, 预览环境就是yarn 构建的, 没有问题 npm 的话, 我刚刚尝试了打包和构建. 也是没有问题的. 我一会把 lock文件传上来. 你更新代码试试 如果是其他的工具的, 欢迎 pr 适配 ![image](https://user-images.githubusercontent.com/59352063/183836482-a5fefd3b-ee59-4401-89ac-b069c7e3dfd9.png)

回大佬，用的pnpm

**Comment by daoxiaonoodles** [comment]
> 你是通过什么安装的依赖? yarn 还是 npm ?

后一个通过pnpm install cropperjs --save 解决了

**Comment by lingting** [comment]
> > 你是通过什么安装的依赖? yarn 还是 npm ?
> 
> 后一个通过pnpm install cropperjs --save 解决了

两个异常都是通过 package.json 中添加对应的依赖的解决的? 0.0 感觉这是工具的问题.

**Comment by daoxiaonoodles** [comment]
> > > 你是通过什么安装的依赖? yarn 还是 npm ?
> > 
> > 
> > 后一个通过pnpm install cropperjs --save 解决了
> 
> 两个异常都是通过 package.json 中添加对应的依赖的解决的? 0.0 感觉这是工具的问题.

应该是，package.json里没有这两个组件，可能是package.json里面有的组件引用的，但是没有拉下来,显式的添加就可以起来了

**Comment by lingting** [comment]
嗯嗯， 我已经把这两个依赖显式声明在 package.json里面了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月10日(周三) 晚上6:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ballcat-projects/ballcat-ui-react] ***@***.***/pro-utils依赖，缺少个文件cropper.css (Issue #10)




    
你是通过什么安装的依赖? yarn 还是 npm ?
  
后一个通过pnpm install cropperjs --save 解决了
  
两个异常都是通过 package.json 中添加对应的依赖的解决的? 0.0 感觉这是工具的问题.
  
应该是，package.json里没有这两个组件，可能是package.json里面有的组件引用的，但是没有拉下来,显式的添加就可以起来了
