### ISSUE TITLE
oss部署

### ISSUE THREAD

**Issue by peiyaoyao** [ballcat-projects/ballcat-ui-react#18]
楼主有antd pro oss部署的方式吗？ 我网上找了好几种方式都不行

**Comment by lingting** [comment]
> 楼主有antd pro oss部署的方式吗？ 我网上找了好几种方式都不行

部署方式和ui框架好像没有任何关系吧?  打包后, dist文件夹压缩扔oss,  服务器上解压不就好了 0.0

**Comment by peiyaoyao** [comment]
打包上传oss使用相对路径,传输到oss后 接口代理地址怎么处理? 因为客户访问地址变成了oss映射的域名，从而访问接口地址也会变成这个域名,这个域名在解析的时候直接指向了oss地址，所以服务器是拦不住这个域名,没法代理的，是否有地方可以在打包完成后配置成固定地址,类似在dev环境下的代理模式

**Comment by lingting** [comment]
> 打包上传oss使用相对路径,传输到oss后 接口代理地址怎么处理? 因为客户访问地址变成了oss映射的域名，从而访问接口地址也会变成这个域名,这个域名在解析的时候直接指向了oss地址，所以服务器是拦不住这个域名,没法代理的，是否有地方可以在打包完成后配置成固定地址,类似在dev环境下的代理模式

这么个用oss部署的方式? 
修改 RequestConfig#13 拼接的 /api 这个为环境变量.  线上环境里面这个变量值为完整的请求域名 试试.

**Comment by peiyaoyao** [comment]
oss部署的话前端所有资源不会占用服务器带宽,而且oss速度会非常快
试了一下,可以了。多谢楼主🙏

**Comment by lingting** [comment]
> oss部署的话前端所有资源不会占用服务器带宽,而且oss速度会非常快 试了一下,可以了。多谢楼主🙏

没事
