### ISSUE TITLE
切换标签页，页面缓存是失败的，而且接口请求2次

### ISSUE THREAD

**Issue by amychuchu** [ballcat-projects/ballcat-ui-react#19]
切换标签页，页面缓存是失败的，而且接口请求2次，react-activation的keeplive报告prolayout组件缓存失败，模板组件多次加载

**Comment by lingting** [comment]
已解决, ,详见 https://github.com/ballcat-projects/ballcat-ui-react/commit/b9c4d6800c049bdb0328062c9f7bb041a923d5a2 目前我在预览环境无法复现.  尝试清除浏览器页面缓存后重试. 还是不行提供下对应浏览器版本
