### ISSUE TITLE
大佬，你的动态路由能单独写个文档吗？

### ISSUE THREAD

**Issue by HalcyonDaysssss** [ballcat-projects/ballcat-ui-react#6]
大佬，你的动态路由能单独写个文档吗？看起来好复杂的样子

**Comment by lingting** [comment]
可以的. 写好了我回复你

**Comment by lingting** [comment]
https://github.com/ballcat-projects/ballcat-doc/blob/master/docs/guide/front/react-antd-pro-v5-dynamic-route.md
