### ISSUE TITLE
【系统菜单】页面内嵌套的菜单下拉列表选择有黏连，返回数据不准确

### ISSUE THREAD

**Issue by bitlin** [ballcat-projects/ballcat-ui-react#7]
![image](https://user-images.githubusercontent.com/14798891/154250676-53c15b36-df93-4848-bcea-8977ede1995c.png)

vue版本也有同样的问题

**Comment by lingting** [comment]
返回数据不准确是指?

**Comment by lingting** [comment]
这个查询接口返回的是选中的任意一个组织的用户. 而不是所有选中组织的共同用户

**Comment by bitlin** [comment]
![image](https://user-images.githubusercontent.com/14798891/154404596-afef11fe-f455-4b4b-9e79-1bc16c751acc.png)

![image](https://user-images.githubusercontent.com/14798891/154404620-a29eae8c-29f1-4726-b355-4f8a5d9a6ebb.png)

![image](https://user-images.githubusercontent.com/14798891/154404660-508b6b82-f84c-43cf-b8b2-7548c55c80d1.png)

![image](https://user-images.githubusercontent.com/14798891/154404718-52ec409f-d347-41b5-8f63-e1ad84a58313.png)

![image](https://user-images.githubusercontent.com/14798891/154404734-e64e75cf-1b9d-404b-9e05-32191f4be99e.png)

![image](https://user-images.githubusercontent.com/14798891/154404781-aabc1ab5-86ef-4a02-9d09-f271d04a2f0e.png)

**Comment by Hccake** [comment]
同时选中【产品研发部】和子选项【Java开发二组】，应该是 1 人

查询条件是，返回 【产品研发部】或者 【Java开发二组】下的用户：例如用户分布如下：

【产品研发部】：`研发总监`
         |------ 【Java开发一组】：`开发 A`
         |------ 【Java开发二组】：`开发 B`

选中 【产品研发部】，展示 `研发总监`
选中 【产品研发部】【Java开发一组】，展示 `研发总监` 和 `开发 A`
选中 【Java开发一组】，展示 `开发 A`
选中 【Java开发一组】【Java开发二组】，展示 `开发 A`  `开发 B`
