### ISSUE TITLE
如果在角色管理界面用户token过期后点击授权按钮会在保持授权窗口开启状态下跳转到登录页面，导致登录页无法操作

### ISSUE THREAD

**Issue by mxsail** [ballcat-projects/ballcat-ui-react#8]
![image](https://user-images.githubusercontent.com/28945708/173273905-7c4e523e-a7e8-4d8f-af9b-11784e41c75c.png)

**Comment by lingting** [comment]
我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ballcat-projects/ballcat-ui-react] 如果在角色管理界面用户token过期后点击授权按钮会在保持授权窗口开启状态下跳转到登录页面，导致登录页无法操作 (Issue #8)

**Comment by lingting** [comment]
![image](https://user-images.githubusercontent.com/59352063/173374891-20dde562-f4d8-4feb-9a41-69bfe4d4617e.png)

已修复, 代码我还没提交. react.ballcat.cn 已经是修复后的版本了,  你强刷下看看还能不能复现这个问题. 没问题我再关issue然后提交代码
