### ISSUE TITLE
前端展示bug,查询接口有数据,前端不展示

### ISSUE THREAD

**Issue by peiyaoyao** [ballcat-projects/ballcat-ui-react#9]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/3918594/175190631-8860d104-ada6-4ecd-b288-6004072a5e4b.png">

**Comment by peiyaoyao** [comment]
另外,这个查询条件 只要数据是二级或者三级的数据,就不会展示

**Comment by lingting** [comment]
好的. 我看看



***@***.***
 
发件人： 裴耀耀
发送时间： 2022-06-23 09:59
收件人： ballcat-projects/ballcat-ui-react
抄送： Subscribed
主题： Re: [ballcat-projects/ballcat-ui-react] 前端展示bug,查询接口有数据,前端不展示 (Issue #9)
另外,这个查询条件 只要数据是二级或者三级的数据,就不会展示

**Comment by lingting** [comment]
已修复
